language: node_js
node_js:
  - "0.11"
  - "0.10"

env:
  global:
    - secure: lVyCPn/MSe+UAvIdFH+SLU7pvA51xPistGGSLaJVxLd5LCz06G3r2WaSvhZBML7fTnU0LvxPxYTcP5fgfQLYrCVQQHC1tBl+ZeUZOhvYuCYawwB5yk81XgPbb7KHrRb482SJimdYZ1awXwvzhU+V2fvriCbJTiX3FVZLltcRrJQ=

after_script: ./node_modules/mocha/bin/mocha -t 5000 --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
